### ISSUE TITLE
TypeError: start() got an unexpected keyword argument 'offset'

### ISSUE THREAD

**Issue by kuklinistvan** [tsudoko/anki-sync-server#51]
I was testing `ankisyncd` against version 2.1.0 [to actually use the version mentioned in README.md](https://github.com/kuklinistvan/docker-anki-sync-server/commit/b68bdcad703b6c8f855060b2d7e029c5dbcf1302#r37096166). Meanwhile it works fine on Android (2.9.1), on AnkiDesktop (2.1.19) I get this message *on the second sync* (after I have confirmed the "Download form AnkiWeb" message):
"Syncing failed:
AnkiWeb encountered an error. Please try again in a few minutes, and if the problem persists, please file a bug report."

Between the two synchronizations I reviewed exactly one card on the desktop side.

```
anki-sync-server_1  | [2020-02-04 17:38:52,250]:INFO:ankisyncd.http:172.20.0.1 "POST /sync/start HTTP/1.1" 500 59
anki-sync-server_1  | [2020-02-04 17:39:35,575]:INFO:ankisyncd.CollectionThread[en]:Running meta(*[], **{'v': 9, 'cv': 'ankidesktop,2.1.19 (3c8690ae),lin:arch:rolling'})
anki-sync-server_1  | [2020-02-04 17:39:35,576]:INFO:ankisyncd.http:172.20.0.1 "POST /sync/meta HTTP/1.1" 200 110
anki-sync-server_1  | [2020-02-04 17:39:35,584]:INFO:ankisyncd.CollectionThread[en]:Running start(*[], **{'minUsn': 100, 'lnewer': True, 'offset': None})
anki-sync-server_1  | [2020-02-04 17:39:35,585]:ERROR:ankisyncd.CollectionThread[en]:Unable to start(*[], **{'minUsn': 100, 'lnewer': True, 'offset': None}): start() got an unexpected keyword argument 'offset'
anki-sync-server_1  | Traceback (most recent call last):
anki-sync-server_1  |   File "/app/anki-sync-server/ankisyncd/thread.py", line 98, in _run
anki-sync-server_1  |     ret = self.wrapper.execute(func, args, kw, return_queue)
anki-sync-server_1  |   File "/app/anki-sync-server/ankisyncd/collection.py", line 44, in execute
anki-sync-server_1  |     ret = func(*args, **kw)
anki-sync-server_1  |   File "/app/anki-sync-server/ankisyncd/sync_app.py", line 626, in run_func
anki-sync-server_1  |     res = handler_method(**keyword_args)
anki-sync-server_1  | TypeError: start() got an unexpected keyword argument 'offset'
anki-sync-server_1  | Traceback (most recent call last):
anki-sync-server_1  |   File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 137, in run
anki-sync-server_1  |     self.result = application(self.environ, self.start_response)
anki-sync-server_1  |   File "/usr/local/lib/python3.7/site-packages/webob/dec.py", line 129, in __call__
anki-sync-server_1  |     resp = self.call_func(req, *args, **kw)
anki-sync-server_1  |   File "/usr/local/lib/python3.7/site-packages/webob/dec.py", line 193, in call_func
anki-sync-server_1  |     return self.func(req, *args, **kwargs)
anki-sync-server_1  |   File "/app/anki-sync-server/ankisyncd/sync_app.py", line 558, in __call__
anki-sync-server_1  |     result = self._execute_handler_method_in_thread(url, data, session)
anki-sync-server_1  |   File "/app/anki-sync-server/ankisyncd/sync_app.py", line 635, in _execute_handler_method_in_thread
anki-sync-server_1  |     result = thread.execute(run_func, kw=keyword_args)
anki-sync-server_1  |   File "/app/anki-sync-server/ankisyncd/thread.py", line 79, in execute
anki-sync-server_1  |     raise ret
anki-sync-server_1  |   File "/app/anki-sync-server/ankisyncd/thread.py", line 98, in _run
anki-sync-server_1  |     ret = self.wrapper.execute(func, args, kw, return_queue)
anki-sync-server_1  |   File "/app/anki-sync-server/ankisyncd/collection.py", line 44, in execute
anki-sync-server_1  |     ret = func(*args, **kw)
anki-sync-server_1  |   File "/app/anki-sync-server/ankisyncd/sync_app.py", line 626, in run_func
anki-sync-server_1  |     res = handler_method(**keyword_args)
anki-sync-server_1  | TypeError: start() got an unexpected keyword argument 'offset'
anki-sync-server_1  | [2020-02-04 17:39:35,586]:INFO:ankisyncd.http:172.20.0.1 "POST /sync/start HTTP/1.1" 500 59
```

**Comment by kuklinistvan** [comment]
(also, I've just noticed that I have misspelled your name on Dockerhub. I'll correct that too in the next release! :))

**Comment by tsdko** [comment]
That's because ankisyncd 2.1.0 does not support syncing Anki 2.1.17 and up. I haven't made a new release because current master has some issues with media sync (e.g. #49, 41205c0b92290bc3dc6e50d401dc9dbf33bdd52c), but it should be possible to apply 2bfccf7fa4af87545f009729ff6e84934c6fde0b on top of 2.1.0 to get 2.1.17+ support.

**Comment by kuklinistvan** [comment]
Okay, 2.1.0 with commit 2bfccf7 seems working - I did not encounter errors while testing.

If it seems alright for you as well, then I think this issue can be closed.
